[theme]
# Primary accent color for interactive elements.
primaryColor = "#F2ACBF"

# Background color for the main content area.
backgroundColor = "#3E4759"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#6BBF90"

# Color used for almost all text.
textColor = "#F2F2F2"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "monospace"
